### ISSUE TITLE
pretrained model on NYU Depth V2

### ISSUE THREAD

**Issue by yulinliutw** [ShreyasSkandanS/DFuseNet#1]
Hello,many thanks that you share your model, the idea is great.
Now I want to test it on the NYU Depth V2 dataset,
Could you provide any pretrained model that can work on the NYU Depth V2?

**Comment by ShreyasSkandanS** [comment]
Hi @yulinliutw,
Thanks for your interest in our work. We are still in the process of tidying up the rest of our code-base and will make this available in the next month or so.
