### ISSUE TITLE
About training settings

### ISSUE THREAD

**Issue by mzy97** [ShreyasSkandanS/DFuseNet#4]
Hi, Thank you for the great work.
In your paper, 20-25 batch size is used, but the KITTI image is large, so what is your hardware setting(what GPU type and GPU memory?) and are you crop the KITTI image to have a large batch size?

**Comment by tyunist** [comment]
We used 3-4 V100 with 32GB memory each.

**Comment by ShreyasSkandanS** [comment]
> We used 3-4 V100 with 32GB memory each.
